# Generated by Django 4.2 on 2023-05-02 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbotapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armenian',
            name='source',
            field=models.ForeignKey(db_column='Source', on_delete=django.db.models.deletion.DO_NOTHING, to='tgbotapp.users', to_field='userid'),
        ),
        migrations.AlterField(
            model_name='english',
            name='source',
            field=models.ForeignKey(db_column='Source', on_delete=django.db.models.deletion.DO_NOTHING, to='tgbotapp.users', to_field='userid'),
        ),
    ]
