# Generated by Django 4.2 on 2023-05-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbotapp', '0002_alter_armenian_source_alter_english_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armenian',
            name='source',
            field=models.TextField(db_column='Source'),
        ),
        migrations.AlterField(
            model_name='english',
            name='source',
            field=models.TextField(db_column='Source'),
        ),
    ]
